version: "3"

services:
  router:
    image: ghcr.io/zuoa/aj-jina-reader:main
    container_name: aj-jina-reader
    restart: "always"
    ports:
      - "6090:6090"
    volumes:
      - ./data:/data
    environment:
      - "TZ=Asia/Shanghai"